version: '3.8'

services:
  messages-service:
    build:
      context: ./messages_service
    ports:
      - "8002:8000"
    container_name: messages_service

  logging-service:
    build:
      context: ./logging_service
    ports:
      - "8001:8000"
    container_name: logging_service

  facade-service:
    build:
      context: ./facade_service
    ports:
      - "8000:8000"
    depends_on:
      - logging-service
      - messages-service
    container_name: facade_service
