services:
  hazelcast1:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast1
    ports:
      - "5701:5701"
    networks:
      - hz-net

  hazelcast2:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast2
    ports:
      - "5702:5701"
    networks:
      - hz-net

  hazelcast3:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast3
    ports:
      - "5703:5701"
    networks:
      - hz-net

  facade:
    build:
      context: ./facade-service
    ports:
      - "8000:8000"
    networks:
      - hz-net

  messages1:
    build:
      context: ./messages-service
    ports:
      - "8001:8000"
    environment:
      - INSTANCE_ID=msg1
    networks:
      - hz-net

  messages2:
    build:
      context: ./messages-service
    ports:
      - "8002:8000"
    environment:
      - INSTANCE_ID=msg2
    networks:
      - hz-net

  logging1:
    build:
      context: ./logging-service
    ports:
      - "8010:8000"
    environment:
      - INSTANCE_ID=log1
    networks:
      - hz-net

  logging2:
    build:
      context: ./logging-service
    ports:
      - "8011:8000"
    environment:
      - INSTANCE_ID=log2
    networks:
      - hz-net

  logging3:
    build:
      context: ./logging-service
    ports:
      - "8012:8000"
    environment:
      - INSTANCE_ID=log3
    networks:
      - hz-net
  
  consul:
    image: hashicorp/consul:1.15
    container_name: consul
    ports:
      - "8500:8500" 
      - "8600:8600/udp" 
    command: "agent -dev -client=0.0.0.0"
    networks:
      - hz-net

networks:
  hz-net:
